#include <iostream>
#include <d3d12.h>
static size_t GetStreamElementSize(uint32_t type) {
    size_t innerSize = 0;
    switch (type) {
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_ROOT_SIGNATURE: innerSize = sizeof(void*); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_VS:
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_PS:
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_DS:
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_HS:
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_GS:
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_CS: innerSize = sizeof(D3D12_SHADER_BYTECODE); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_STREAM_OUTPUT: innerSize = sizeof(D3D12_STREAM_OUTPUT_DESC); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_BLEND: innerSize = sizeof(D3D12_BLEND_DESC); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_SAMPLE_MASK: innerSize = sizeof(UINT); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_RASTERIZER: innerSize = sizeof(D3D12_RASTERIZER_DESC); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL: innerSize = sizeof(D3D12_DEPTH_STENCIL_DESC); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_INPUT_LAYOUT: innerSize = sizeof(D3D12_INPUT_LAYOUT_DESC); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_IB_STRIP_CUT_VALUE: innerSize = sizeof(D3D12_INDEX_BUFFER_STRIP_CUT_VALUE); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_PRIMITIVE_TOPOLOGY: innerSize = sizeof(D3D12_PRIMITIVE_TOPOLOGY_TYPE); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_RENDER_TARGET_FORMATS: innerSize = sizeof(D3D12_RT_FORMAT_ARRAY); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL_FORMAT: innerSize = sizeof(DXGI_FORMAT); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_SAMPLE_DESC: innerSize = sizeof(DXGI_SAMPLE_DESC); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_NODE_MASK: innerSize = sizeof(UINT); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_CACHED_PSO: innerSize = sizeof(D3D12_CACHED_PIPELINE_STATE); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_FLAGS: innerSize = sizeof(D3D12_PIPELINE_STATE_FLAGS); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_DEPTH_STENCIL1: innerSize = sizeof(D3D12_DEPTH_STENCIL_DESC1); break;
    case D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_VIEW_INSTANCING: innerSize = sizeof(D3D12_VIEW_INSTANCING_DESC); break;
    case 24: /* AS */ innerSize = sizeof(D3D12_SHADER_BYTECODE); break;
    case 25: /* MS */ innerSize = sizeof(D3D12_SHADER_BYTECODE); break;
    default: return 0;
    }
    return (sizeof(void*) + innerSize + 7) & ~7;
}

int main() {
    std::cout << "CS size: " << GetStreamElementSize(D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_CS) << "\n";
    std::cout << "BLEND size: " << GetStreamElementSize(D3D12_PIPELINE_STATE_SUBOBJECT_TYPE_BLEND) << "\n";
    return 0;
}
